"use client";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
export default function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
  originalFileUrl,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
  originalFileUrl: string;
}) {
  const handleDownload = () => {
    try {
      // Prepare the summary content
      const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
  
${summaryText}
  
Original File: ${fileName}
Generated by Saramsa
  `;

      // Create a Blob from the summary content
      const blob = new Blob([summaryContent], { type: "text/plain" });

      // Create a URL for the Blob object
      const url = URL.createObjectURL(blob);

      // Sanitize the title for file naming
      const sanitizedTitle = title.replace(/[^a-z0-9]/gi, "_");

      // Create a download link
      const link = document.createElement("a");
      link.href = url;
      link.download = `Summary-${sanitizedTitle}.txt`;

      // Append the link to the body, click it, and remove it after the download
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      // Revoke the Object URL to free up memory after the download
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Error while downloading the summary:", error);
    }
  };

  return (
    <Button
      size="sm"
      className="h-8 px-3 bg-rose-100 text-rose-600
  hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
